# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('weibo_id', models.CharField(blank=True, max_length=30, verbose_name='新浪微博')),
                ('blog', models.CharField(blank=True, max_length=200, verbose_name='个人网站')),
                ('location', models.CharField(blank=True, max_length=10, verbose_name='城市')),
                ('profile', models.CharField(blank=True, max_length=140, verbose_name='个人简介')),
                ('avatar', models.CharField(blank=True, max_length=128, verbose_name='头像')),
                ('au', models.IntegerField(default=True, verbose_name='用户活跃度')),
                ('last_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='上次访问IP')),
                ('email_verified', models.BooleanField(default=False, verbose_name='邮箱是否验证')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='用户注册时间')),
                ('topic_num', models.IntegerField(default=0, verbose_name='帖子数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=None, max_length=32, verbose_name='Email 验证 token')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FindPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_a', to=settings.AUTH_USER_MODEL, verbose_name='偶像')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_b', to=settings.AUTH_USER_MODEL, verbose_name='粉丝')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set([('user_a', 'user_b')]),
        ),
    ]
